### PR TITLE
Dop/accuracy issues

### PR DESCRIPTION
**Pull request by doneill**
Looking for a review to verify this [issue](https://issuetracker.google.com/u/0/issues/79189573).

`mCurrentLocation.getAccuracy()` never reports accuracy < 10M

### CODE REVIEW

**Comment by doneill** [comment]
Reproducible test case for #151

**Comment by doneill** [comment]
Can anyone verify the issue in this PR?

**Comment by doneill** [comment]
Could someone please comment or provide an update with this issue/PR?

**Comment by mirko77** [comment]
Any news on this? We have thousands of users affected on our app.

**Comment by doneill** [comment]
Duplicated comment I made on the PR, there is an update with Play Services 14.3.66+ whereby accuracy is being reported to 3M now, which is progress but still trying to inquire as to why limit the accuracy to 3M?  And if this is something that will continue to improve over time?

**Comment by mirko77** [comment]
> Duplicated comment I made on the issue, there is an update with Play Services 14.3.66+ whereby accuracy is being reported to 3M now, which is progress but still trying to inquire as to why limit the accuracy to 3M? And if this is something that will continue to improve over time?

The limit is 3M on consumer device, yes.

**Comment by doneill** [comment]
Closing

Original [issue](https://issuetracker.google.com/u/0/issues/79189573) fixed
Continued 3M limitation [issue](https://issuetracker.google.com/issues/118789585) marked as **Won't Fix (Intended behavior)**

**Pull request closed without merging**
